### ISSUE TITLE
Panic due to flag redefined: sweep 

### ISSUE THREAD

**Issue by NeilW** [hashicorp/terraform-plugin-testing#155]
### terraform-plugin-testing version

```
1.4.0
```

### Relevant provider source code

```go
package provider

import (
	"testing"

	"github.com/hashicorp/terraform-plugin-go/tfprotov5"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
)

func TestMuxServer(t *testing.T) {
	resource.Test(t, resource.TestCase{
		ProtoV5ProviderFactories: map[string]func() (tfprotov5.ProviderServer, error){
			"brightbox": func() (tfprotov5.ProviderServer, error) {
				providerServerCreator, err := BrightboxTF5ProviderServerCreatorFactory("test")
				if err != nil {
					return nil, err
				}
				return providerServerCreator(), nil
			},
		},
		Steps: []resource.TestStep{
			{
				Config: `resource "brightbox_server_group" "default" {
						  name = "Used by the terraform"
						}`,
			},
		},
	})
}

package provider

import (
	"context"

	sdkprovider "github.com/brightbox/terraform-provider-brightbox/brightbox"
	"github.com/hashicorp/terraform-plugin-framework/providerserver"
	"github.com/hashicorp/terraform-plugin-go/tfprotov5"
	"github.com/hashicorp/terraform-plugin-mux/tf5muxserver"
)

// BrightboxTF5ProviderServerCreatorFactory returns a function that will create a
// Provider Server.
func BrightboxTF5ProviderServerCreatorFactory(name string) (func() tfprotov5.ProviderServer, error) {
	ctx := context.Background()
	providers := []func() tfprotov5.ProviderServer{
		sdkprovider.Provider().GRPCProvider,    //SDK Brightbox provider
		providerserver.NewProtocol5(New(name)), // This provider
	}

	muxServer, err := tf5muxserver.NewMuxServer(ctx, providers...)

	if err != nil {
		return nil, err
	}

	return muxServer.ProviderServer, nil
}


```

### Expected Behavior
Provider test runs 

### Actual Behavior
$ go test
/tmp/go-build1374472121/b001/provider.test flag redefined: sweep
panic: /tmp/go-build1374472121/b001/provider.test flag redefined: sweep

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc000124120, {0x1146318, 0xc0002af8b0}, {0xfbc5a0, 0x5}, {0xfe58de, 0x29})
	/snap/go/current/src/flag/flag.go:982 +0x2f9
flag.(*FlagSet).StringVar(...)
	/snap/go/current/src/flag/flag.go:847
flag.(*FlagSet).String(0x8?, {0xfbc5a0, 0x5}, {0x0, 0x0}, {0xfe58de, 0x29})
	/snap/go/current/src/flag/flag.go:860 +0xac
flag.String(...)
	/snap/go/current/src/flag/flag.go:867
github.com/hashicorp/terraform-plugin-testing/helper/resource.init()
	/home/neil/Go/pkg/mod/github.com/hashicorp/terraform-plugin-testing@v1.4.0/helper/resource/testing.go:55 +0x45
exit status 2
FAIL	github.com/brightbox/terraform-provider-brightbox/internal/provider	0.010s

### Steps to Reproduce
go test

**Comment by bendbennett** [comment]
Hi @NeilW 👋 

I think the likely explanation for the panic you are seeing is because you are importing `github.com/hashicorp/terraform-plugin-testing/helper/resource` and in the `sdkprovider` (i.e., `github.com/brightbox/terraform-provider-brightbox/brightbox`) you are using `github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource` for example in [resource_brightbox_server.go](https://github.com/brightbox/terraform-provider-brightbox/blob/b43b84eba15022dddfd815c1331d13ba6dae899b/brightbox/resource_brightbox_server_group.go#L11C1-L11C1).

You should be able to migrate your acceptance testing dependencies in `terraform-provider-brightbox` from SDKv2 to the Plugin Testing module by following [these steps](https://developer.hashicorp.com/terraform/plugin/testing/migrating).

**Comment by NeilW** [comment]
Really not sure how I missed that. Thanks
